name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ocaml-version: ['4.09.0']
    steps:
      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - uses: actions/checkout@v1

      - name: Pin package
        run: opam pin add inquire.dev -n .

      - name: Query and install external dependencies
        run: opam depext -yt inquire

      - name: Install dependencies
        run: opam install -t . --deps-only

      - name: Build
        run: opam exec -- make

      - name: Run tests
        run: opam exec -- make test

      - name: Build documentation
        run: opam exec -- make doc

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build/default/_doc/_html/
